Update continuosintegration.yml
correção 2

diff --git a/.github/workflows/continuosintegration.yml b/.github/workflows/continuosintegration.yml
--- a/.github/workflows/continuosintegration.yml
+++ b/.github/workflows/continuosintegration.yml
@@ -17,6 +17,13 @@ jobs:
         with:
           python-version: '3.x'
 
+      - name: Verify requirements.txt exists
+        run: |
+          if [ ! -f requirements.txt ]; then
+            echo "requirements.txt not found!"
+            exit 1
+          fi
+
       - name: Install dependencies
         run: pip install -r requirements.txt
 
